# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.11-slim
RUN apt update
RUN apt install git-all -y
RUN pip install \
    dagster==1.7.15\
    dagster-graphql==1.7.15 \
    dagster-webserver==1.7.15 \
    dagster-postgres==0.23.15 \
    dagster-docker==0.23.15 \
    dbt-core==1.8.4 \
    dbt-postgres==1.8.2 \    
    dagster-dbt==0.23.15 
# RUN pip freeze

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME
RUN mkdir -p /root/.dbt

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

